# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f7e2df3095cf8a9e853d84110fdf368094bdf14744dc3bca9dda6ddbf609cc6aad7c173cec8383ca6761532ff6a0217fa6ec6e316e5ddc28fb4cf7232b1af03

test:
  secret_key_base: 61593064170bc1d9fbdf18c85516cf5ac98022314384bbc38cd2ea1ec7a3ce3f0e4e0d21b7eec54f646bbffaa4ea86ccec08e0be30ada8f25817bd7baa64a35a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 61593064170bc1d9fbdf18c85516cf5ac98022314384bbc38cd2ea1ec7a3ce3f0e4e0d21b7eec54f646bbffaa4ea86ccec08e0be30ada8f25817bd7baa64a35a
